Meshes:
  - Name: 'Qrcode'
    FbxPath: "/home/agathe/code/parrot-olympe/olympe/files/qr_code_3d_brut.fbx"
    Location: "-330 0 90"  # The position in the 3D space
    Rotation: "90 90 0"  # The orientation of the mesh
    Scale: "1 1 1"  # The scale of the mesh
    SnapToGround: false  # Whether to snap to the ground or float
  - Name: 'FondBlanc'
    FbxPath: "/home/agathe/code/parrot-olympe/olympe/files/fond_blanc.fbx"
    Location: "-400 0 90"  # The position in the 3D space
    Rotation: "90 90 0"  # The orientation of the mesh
    Scale: "1 1 1"  # The scale of the mesh
    SnapToGround: false  # Whether to snap to the ground or float

